//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenApi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenApi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.OpenApi", typeof(OpenApi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAPI.
        /// </summary>
        public static string OpenApiHeader {
            get {
                return ResourceManager.GetString("OpenApiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specification for the selected resource.
        /// </summary>
        public static string OpenApiNoSpecificationForResource {
            get {
                return ResourceManager.GetString("OpenApiNoSpecificationForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} OpenAPI.
        /// </summary>
        public static string OpenApiPageTitle {
            get {
                return ResourceManager.GetString("OpenApiPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit headers.
        /// </summary>
        public static string OpenApiRequestButtonEditHeadersText {
            get {
                return ResourceManager.GetString("OpenApiRequestButtonEditHeadersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameters.
        /// </summary>
        public static string OpenApiRequestButtonEditParametersText {
            get {
                return ResourceManager.GetString("OpenApiRequestButtonEditParametersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a method.
        /// </summary>
        public static string OpenApiSelectAMethod {
            get {
                return ResourceManager.GetString("OpenApiSelectAMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a resource to view OpenAPI specifications.
        /// </summary>
        public static string OpenApiSelectAResource {
            get {
                return ResourceManager.GetString("OpenApiSelectAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select method..
        /// </summary>
        public static string OpenApiSelectMethod {
            get {
                return ResourceManager.GetString("OpenApiSelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resource.
        /// </summary>
        public static string OpenApiSelectResourceToolbar {
            get {
                return ResourceManager.GetString("OpenApiSelectResourceToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string OpenApiSendRequest {
            get {
                return ResourceManager.GetString("OpenApiSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string OpenApiServerLabel {
            get {
                return ResourceManager.GetString("OpenApiServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown state.
        /// </summary>
        public static string OpenApiUnknownState {
            get {
                return ResourceManager.GetString("OpenApiUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View attributes.
        /// </summary>
        public static string OpenApiViewAttributesToolbar {
            get {
                return ResourceManager.GetString("OpenApiViewAttributesToolbar", resourceCulture);
            }
        }
    }
}
